name: secret_sharing
version: 0.1.0
author: Axel Christ <adracus@gmail.com>
description: Implementation of Shamirs Secret Sharing algorithm
homepage: https://github.com/duse-io/secret-sharing-dart
documentation: https://github.com/duse-io/secret-sharing-dart
dependencies:
  args: '>=0.12.0+2 <0.13.0'
  bbs: '>=0.0.1 < 0.1.0'
  logging: '>=0.9.2 <0.10.0'
dev_dependencies:
  mock: '>=0.11.0+2 <0.12.0'
  unittest: ">=0.11.5+4 <0.12.0"
